name: connectinno_notes_app
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  dio: ^5.9.0
  go_router: ^16.2.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  connectivity_plus: ^6.1.5
  flutter_secure_storage: ^9.2.4
  drift: ^2.28.1
  sqlite3_flutter_libs: ^0.5.39
  path: ^1.9.1
  path_provider: ^2.1.5
  drift_dev: ^2.28.1
  internet_connection_checker_plus: ^2.7.2
  flutter_staggered_grid_view: ^0.7.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  build_runner: ^2.7.1

  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
