// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA74gk_qNKWBWOl3t74FdF6Z8tCz8GA4m0',
    appId: '1:1033524580637:web:be5f861ec03be8fa9791f4',
    messagingSenderId: '1033524580637',
    projectId: 'connectinno-notes',
    authDomain: 'connectinno-notes.firebaseapp.com',
    storageBucket: 'connectinno-notes.firebasestorage.app',
    measurementId: 'G-0MEGJ1CY0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPnIwiu9pmXwu9llB2XEuX_TcQdevsNZ8',
    appId: '1:1033524580637:android:62ea1691e442cd4c9791f4',
    messagingSenderId: '1033524580637',
    projectId: 'connectinno-notes',
    storageBucket: 'connectinno-notes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoC_60TfjbO8Q6_wwhIUBe8k3OHRBNSNM',
    appId: '1:1033524580637:ios:c426a1d35dcaca699791f4',
    messagingSenderId: '1033524580637',
    projectId: 'connectinno-notes',
    storageBucket: 'connectinno-notes.firebasestorage.app',
    iosBundleId: 'com.connectinno.notes.connectinnoNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoC_60TfjbO8Q6_wwhIUBe8k3OHRBNSNM',
    appId: '1:1033524580637:ios:c426a1d35dcaca699791f4',
    messagingSenderId: '1033524580637',
    projectId: 'connectinno-notes',
    storageBucket: 'connectinno-notes.firebasestorage.app',
    iosBundleId: 'com.connectinno.notes.connectinnoNotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA74gk_qNKWBWOl3t74FdF6Z8tCz8GA4m0',
    appId: '1:1033524580637:web:b60070131116fe119791f4',
    messagingSenderId: '1033524580637',
    projectId: 'connectinno-notes',
    authDomain: 'connectinno-notes.firebaseapp.com',
    storageBucket: 'connectinno-notes.firebasestorage.app',
    measurementId: 'G-D501B7Z0T1',
  );
}
